/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch design system palette
        "surface":                "#131313",
        "surface-dim":            "#131313",
        "surface-bright":         "#393939",
        "surface-container":      "#1f2020",
        "surface-container-low":  "#1b1c1c",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "surface-container-lowest":  "#0e0e0e",
        "surface-variant":        "#353535",
        "background":             "#131313",
        "on-background":          "#e5e2e1",
        "on-surface":             "#e5e2e1",
        "on-surface-variant":     "#c4c7c8",
        "outline":                "#8e9192",
        "outline-variant":        "#444748",
        "primary":                "#ffffff",
        "on-primary":             "#2f3131",
        "primary-container":      "#e2e2e2",
        "primary-fixed":          "#e2e2e2",
        "primary-fixed-dim":      "#c6c6c7",
        "secondary":              "#5cde94",
        "on-secondary":           "#00391e",
        "secondary-container":    "#06a662",
        "secondary-fixed":        "#7afbae",
        "secondary-fixed-dim":    "#5cde94",
        "error":                  "#f87171",
        "on-error":               "#690005",
        "error-container":        "#93000a",
        "inverse-surface":        "#e5e2e1",
        "inverse-on-surface":     "#303030",
        "inverse-primary":        "#5d5f5f",
        "surface-tint":           "#c6c6c7",
        // Legacy slate colours kept for backward compat with existing components
        "slate-950": "#020617",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "unit": "4px",
        "gutter": "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "container-padding": "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        sans:  ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono:  ["JetBrains Mono", "ui-monospace", "monospace"],
        // Named font families from Stitch
        "display":     ["JetBrains Mono", "monospace"],
        "headline-lg": ["JetBrains Mono", "monospace"],
        "headline-md": ["JetBrains Mono", "monospace"],
        "body-lg":     ["JetBrains Mono", "monospace"],
        "body-md":     ["JetBrains Mono", "monospace"],
        "data-mono":   ["JetBrains Mono", "monospace"],
        "label-caps":  ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display":     ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg":     ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md":     ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "data-mono":   ["14px", { lineHeight: "1", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-caps":  ["11px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
